### ISSUE TITLE
SCP-049 cannot revive dead zombies

### ISSUE THREAD

**Issue by Wilnath** [zochris/SCPSL-SpectatorDisabler#63]
### What happened?

In basegame without this plugin SCP-049 is able to revive zombies killed by humans three times, after of which reviving it says "This soul has been revived too many times."
Doing this also lowers the max HP of the zombie more and more for each time it gets revived.

With this plugin attempting to revive a zombie as soon as it dies gives "This soul is no longer with us." Disallowing subsequent revives of players entirely.

### SCP:SL version

13.4.2

### EXILED version

8.8.0

### SpectatorDisabler version

3.0.1

**Comment by zochris** [comment]
Fixed by #64
