### ISSUE TITLE
SCP version 14.0 porting

### ISSUE THREAD

**Issue by Wilnath** [zochris/SCPSL-SpectatorDisabler#80]
### What happened?

I'm going to compile the issues I run into going from old scp version into the 14.0 beta with this plugin, aswell as trying my best to see if they can be fixed easily:

1. RespawnManager.CheckSpawnable has moved, but it looks like this is fixed by just updating the harmony patch target to its new location WaveSpawner.CheckSpawnable
2. Scp049ResurrectOnRoleChangedPatch and Scp049OnServerRoleSetPatch have had their compiled function names changed, just change 22 to 28 in TargetMethod and it'll work
3. They've changed all the wall weapon offsets and positions, not normalized, just seemingly randomly changed 🙂 , i just readjusted them a bit and now they're fine
4. (Wall weapons are also broken and act weird on pick up, checked it out and root cause is a bug in EXILED that already has a pr to be fixed)

I've made a local repo with these fixed, it's probably a good idea to get a scpsl-14 branch going in preparation for the update but dunno if I can set that up from my side

This *seemingly* works, both large and small waves act properly like this, but I haven't fully tested if the new token system plays well, mostly because I just don't quite understand it yet

### SCP:SL version

14.0 public beta

### EXILED version

9.0.0-alpha3

### SpectatorDisabler version

latest master branch

**Comment by zochris** [comment]
I created the `scpsl-14.0-update` branch for patches during the beta phase.

Do you happen to know if the dedicated server tool also has a beta branch for the 14 update?
